services:

  swarm-manager:
    image: docker:24-dind
    container_name: swarm_manager
    privileged: true
    command: sh /epinfo/backend/manager.sh
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - manager_data:/var/lib/docker
      - ./backend:/epinfo/backend:ro
      - ./frontend:/epinfo/frontend:ro
      - ./banco_de_dados:/epinfo/banco_de_dados:ro
      - ./docker-stack.yml:/epinfo/docker-stack.yml:ro
      - image_share:/epinfo/images
      - token_share:/epinfo/token
    networks:
      dind_net:
        aliases:
          - manager
    ports:
      - "80:80"
      - "2377:2377"

  swarm-worker-1:
    image: docker:24-dind
    container_name: swarm_worker_1
    privileged: true
    command: sh /epinfo/backend/worker.sh
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - worker1_data:/var/lib/docker
      - ./backend:/epinfo/backend:ro
      - image_share:/epinfo/images:ro
      - token_share:/epinfo/token:ro
    networks:
      dind_net:
        aliases:
          - worker1
    depends_on:
      - swarm-manager

  swarm-worker-2:
    image: docker:24-dind
    container_name: swarm_worker_2
    privileged: true
    command: sh /epinfo/backend/worker.sh
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - worker2_data:/var/lib/docker
      - ./backend:/epinfo/backend:ro
      - image_share:/epinfo/images:ro
      - token_share:/epinfo/token:ro
    networks:
      dind_net:
        aliases:
          - worker2
    depends_on:
      - swarm-manager

volumes:
  manager_data:
  worker1_data:
  worker2_data:
  image_share:
  token_share:

networks:
  dind_net:
    driver: bridge
